### ISSUE TITLE
Option to place a project under multiple categories

### ISSUE THREAD

**Issue by agjtimmers** [sodascience/awesome-citizen-science-projects#7]
I would like to categorize the project Fishing in the Past under both History and Ecology. Is this possible and how would I do that?

**Comment by leonardovida** [comment]
At the moment it is not possible. We might decide to add a new column to the csv called something like `alternative_categories` to allow for multiple categorization. However, a main category always need to be selected.

**Comment by J535D165** [comment]
I like the idea of additional categories. I would use `extra_categories` instead of *alternative*.
